// <auto-generated />
using System;
using Labs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labs.Data.Migrations
{
    [DbContext(typeof(ReservationContext))]
    [Migration("20251024095943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labs.Domain.Entities.Destination", b =>
                {
                    b.Property<Guid>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Latin1_General_CI_AS");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.HasKey("DestinationId");

                    b.HasIndex("DestinationName")
                        .IsUnique();

                    b.HasIndex("Distance");

                    b.ToTable("Destination", (string)null);

                    b.HasData(
                        new
                        {
                            DestinationId = new Guid("88888888-8888-8888-8888-888888888888"),
                            BasePrice = 0m,
                            DestinationName = "Київ",
                            Distance = 0
                        },
                        new
                        {
                            DestinationId = new Guid("99999999-9999-9999-9999-999999999999"),
                            BasePrice = 450m,
                            DestinationName = "Львів",
                            Distance = 540
                        },
                        new
                        {
                            DestinationId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BasePrice = 380m,
                            DestinationName = "Одеса",
                            Distance = 440
                        },
                        new
                        {
                            DestinationId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BasePrice = 400m,
                            DestinationName = "Харків",
                            Distance = 480
                        });
                });

            modelBuilder.Entity("Labs.Domain.Entities.Passenger", b =>
                {
                    b.Property<Guid>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("PassengerId");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Passenger", (string)null);

                    b.HasData(
                        new
                        {
                            PassengerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Address = "вул. Хрещатик, 1, Київ",
                            FirstName = "Іван",
                            LastName = "Петренко",
                            MiddleName = "Васильович",
                            PhoneNumber = "+380501234567"
                        },
                        new
                        {
                            PassengerId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Address = "вул. Шевченка, 5, Львів",
                            FirstName = "Марія",
                            LastName = "Коваленко",
                            MiddleName = "Олександрівна",
                            PhoneNumber = "+380672345678"
                        },
                        new
                        {
                            PassengerId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Address = "вул. Дерибасівська, 10, Одеса",
                            FirstName = "Петро",
                            LastName = "Сидоренко",
                            MiddleName = "Іванович",
                            PhoneNumber = "+380633456789"
                        },
                        new
                        {
                            PassengerId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Address = "вул. Сумська, 15, Харків",
                            FirstName = "Ольга",
                            LastName = "Тимошенко",
                            MiddleName = "Михайлівна",
                            PhoneNumber = "+380994567890"
                        },
                        new
                        {
                            PassengerId = new Guid("10101010-1010-1010-1010-101010101010"),
                            Address = "вул. Independece, 20, Київ",
                            FirstName = "Андрій",
                            LastName = "Мельник",
                            MiddleName = "Сергійович",
                            PhoneNumber = "+380955678901"
                        });
                });

            modelBuilder.Entity("Labs.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivalDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UrgencySurcharge")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("WagonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TicketId");

                    b.HasIndex("DepartureDateTime");

                    b.HasIndex("DestinationId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("TrainId");

                    b.HasIndex("WagonId");

                    b.HasIndex("TrainId", "DepartureDateTime");

                    b.ToTable("Ticket", (string)null);

                    b.HasData(
                        new
                        {
                            TicketId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ArrivalDateTime = new DateTime(2025, 12, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDateTime = new DateTime(2025, 12, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PassengerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            TotalPrice = 620m,
                            TrainId = new Guid("20202020-2020-2020-2020-202020202020"),
                            UrgencySurcharge = 20m,
                            WagonId = new Guid("50505050-5050-5050-5050-505050505050")
                        },
                        new
                        {
                            TicketId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ArrivalDateTime = new DateTime(2025, 12, 8, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDateTime = new DateTime(2025, 12, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PassengerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            TotalPrice = 430m,
                            TrainId = new Guid("30303030-3030-3030-3030-303030303030"),
                            UrgencySurcharge = 0m,
                            WagonId = new Guid("70707070-7070-7070-7070-707070707070")
                        },
                        new
                        {
                            TicketId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            ArrivalDateTime = new DateTime(2025, 12, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDateTime = new DateTime(2025, 12, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            PassengerId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            TotalPrice = 600m,
                            TrainId = new Guid("40404040-4040-4040-4040-404040404040"),
                            UrgencySurcharge = 50m,
                            WagonId = new Guid("90909090-9090-9090-9090-909090909090")
                        },
                        new
                        {
                            TicketId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            ArrivalDateTime = new DateTime(2025, 12, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDateTime = new DateTime(2025, 12, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PassengerId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            TotalPrice = 750m,
                            TrainId = new Guid("20202020-2020-2020-2020-202020202020"),
                            UrgencySurcharge = 0m,
                            WagonId = new Guid("60606060-6060-6060-6060-606060606060")
                        },
                        new
                        {
                            TicketId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ArrivalDateTime = new DateTime(2025, 12, 4, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDateTime = new DateTime(2025, 12, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PassengerId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            TotalPrice = 400m,
                            TrainId = new Guid("30303030-3030-3030-3030-303030303030"),
                            UrgencySurcharge = 20m,
                            WagonId = new Guid("80808080-8080-8080-8080-808080808080")
                        },
                        new
                        {
                            TicketId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            ArrivalDateTime = new DateTime(2025, 12, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDateTime = new DateTime(2025, 12, 21, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            PassengerId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            TotalPrice = 550m,
                            TrainId = new Guid("40404040-4040-4040-4040-404040404040"),
                            UrgencySurcharge = 0m,
                            WagonId = new Guid("90909090-9090-9090-9090-909090909090")
                        },
                        new
                        {
                            TicketId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            ArrivalDateTime = new DateTime(2025, 12, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDateTime = new DateTime(2025, 12, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PassengerId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            TotalPrice = 620m,
                            TrainId = new Guid("20202020-2020-2020-2020-202020202020"),
                            UrgencySurcharge = 20m,
                            WagonId = new Guid("50505050-5050-5050-5050-505050505050")
                        },
                        new
                        {
                            TicketId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            ArrivalDateTime = new DateTime(2025, 12, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDateTime = new DateTime(2025, 12, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            PassengerId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            TotalPrice = 450m,
                            TrainId = new Guid("30303030-3030-3030-3030-303030303030"),
                            UrgencySurcharge = 0m,
                            WagonId = new Guid("70707070-7070-7070-7070-707070707070")
                        },
                        new
                        {
                            TicketId = new Guid("e1111111-1111-1111-1111-111111111111"),
                            ArrivalDateTime = new DateTime(2025, 12, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDateTime = new DateTime(2025, 12, 7, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PassengerId = new Guid("10101010-1010-1010-1010-101010101010"),
                            TotalPrice = 530m,
                            TrainId = new Guid("40404040-4040-4040-4040-404040404040"),
                            UrgencySurcharge = 20m,
                            WagonId = new Guid("90909090-9090-9090-9090-909090909090")
                        },
                        new
                        {
                            TicketId = new Guid("e2222222-2222-2222-2222-222222222222"),
                            ArrivalDateTime = new DateTime(2025, 12, 31, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDateTime = new DateTime(2025, 12, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PassengerId = new Guid("10101010-1010-1010-1010-101010101010"),
                            TotalPrice = 750m,
                            TrainId = new Guid("20202020-2020-2020-2020-202020202020"),
                            UrgencySurcharge = 0m,
                            WagonId = new Guid("60606060-6060-6060-6060-606060606060")
                        });
                });

            modelBuilder.Entity("Labs.Domain.Entities.Train", b =>
                {
                    b.Property<Guid>("TrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TrainNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .UseCollation("Latin1_General_CI_AS");

                    b.Property<Guid>("TrainTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TrainId");

                    b.HasIndex("TrainNumber")
                        .IsUnique();

                    b.HasIndex("TrainTypeId");

                    b.ToTable("Train", (string)null);

                    b.HasData(
                        new
                        {
                            TrainId = new Guid("20202020-2020-2020-2020-202020202020"),
                            TrainNumber = "001IC",
                            TrainTypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            TrainId = new Guid("30303030-3030-3030-3030-303030303030"),
                            TrainNumber = "123",
                            TrainTypeId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            TrainId = new Guid("40404040-4040-4040-4040-404040404040"),
                            TrainNumber = "777",
                            TrainTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Labs.Domain.Entities.TrainType", b =>
                {
                    b.Property<Guid>("TrainTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_CI_AS");

                    b.HasKey("TrainTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("TrainType", (string)null);

                    b.HasData(
                        new
                        {
                            TrainTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TypeName = "Швидкісний"
                        },
                        new
                        {
                            TrainTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TypeName = "Інтерсіті"
                        },
                        new
                        {
                            TrainTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TypeName = "Пасажирський"
                        });
                });

            modelBuilder.Entity("Labs.Domain.Entities.Wagon", b =>
                {
                    b.Property<Guid>("WagonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WagonNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .UseCollation("Latin1_General_CI_AS");

                    b.Property<Guid>("WagonTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WagonId");

                    b.HasIndex("WagonTypeId");

                    b.HasIndex("TrainId", "WagonNumber")
                        .IsUnique();

                    b.ToTable("Wagon", (string)null);

                    b.HasData(
                        new
                        {
                            WagonId = new Guid("50505050-5050-5050-5050-505050505050"),
                            TrainId = new Guid("20202020-2020-2020-2020-202020202020"),
                            WagonNumber = "1",
                            WagonTypeId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            WagonId = new Guid("60606060-6060-6060-6060-606060606060"),
                            TrainId = new Guid("20202020-2020-2020-2020-202020202020"),
                            WagonNumber = "2",
                            WagonTypeId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            WagonId = new Guid("70707070-7070-7070-7070-707070707070"),
                            TrainId = new Guid("30303030-3030-3030-3030-303030303030"),
                            WagonNumber = "1",
                            WagonTypeId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            WagonId = new Guid("80808080-8080-8080-8080-808080808080"),
                            TrainId = new Guid("30303030-3030-3030-3030-303030303030"),
                            WagonNumber = "2",
                            WagonTypeId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            WagonId = new Guid("90909090-9090-9090-9090-909090909090"),
                            TrainId = new Guid("40404040-4040-4040-4040-404040404040"),
                            WagonNumber = "1",
                            WagonTypeId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("Labs.Domain.Entities.WagonType", b =>
                {
                    b.Property<Guid>("WagonTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Surcharge")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("WagonTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_CI_AS");

                    b.HasKey("WagonTypeId");

                    b.HasIndex("WagonTypeName")
                        .IsUnique();

                    b.ToTable("WagonType", (string)null);

                    b.HasData(
                        new
                        {
                            WagonTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Surcharge = 0m,
                            WagonTypeName = "Загальний"
                        },
                        new
                        {
                            WagonTypeId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Surcharge = 50m,
                            WagonTypeName = "Плацкартний"
                        },
                        new
                        {
                            WagonTypeId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Surcharge = 150m,
                            WagonTypeName = "Купе"
                        },
                        new
                        {
                            WagonTypeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Surcharge = 300m,
                            WagonTypeName = "Люкс"
                        });
                });

            modelBuilder.Entity("Labs.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Labs.Domain.Entities.Destination", "Destination")
                        .WithMany("Tickets")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Labs.Domain.Entities.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Labs.Domain.Entities.Train", "Train")
                        .WithMany("Tickets")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Labs.Domain.Entities.Wagon", "Wagon")
                        .WithMany("Tickets")
                        .HasForeignKey("WagonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Passenger");

                    b.Navigation("Train");

                    b.Navigation("Wagon");
                });

            modelBuilder.Entity("Labs.Domain.Entities.Train", b =>
                {
                    b.HasOne("Labs.Domain.Entities.TrainType", "TrainType")
                        .WithMany("Trains")
                        .HasForeignKey("TrainTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainType");
                });

            modelBuilder.Entity("Labs.Domain.Entities.Wagon", b =>
                {
                    b.HasOne("Labs.Domain.Entities.Train", "Train")
                        .WithMany("Wagons")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Labs.Domain.Entities.WagonType", "WagonType")
                        .WithMany("Wagons")
                        .HasForeignKey("WagonTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Train");

                    b.Navigation("WagonType");
                });

            modelBuilder.Entity("Labs.Domain.Entities.Destination", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Labs.Domain.Entities.Passenger", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Labs.Domain.Entities.Train", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("Wagons");
                });

            modelBuilder.Entity("Labs.Domain.Entities.TrainType", b =>
                {
                    b.Navigation("Trains");
                });

            modelBuilder.Entity("Labs.Domain.Entities.Wagon", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Labs.Domain.Entities.WagonType", b =>
                {
                    b.Navigation("Wagons");
                });
#pragma warning restore 612, 618
        }
    }
}
